export const UPDATE_FORM_REGISTER = 'UPDATE_FORM_REGISTER';
export const UPDATE_BIRTHDAY_REGISTER = 'UPDATE_BIRTHDAY_REGISTER';
export const UPDATE_ERROR_STATUS_REGISTER = 'UPDATE_ERROR_STATUS_REGISTER';
export const UPDATE_STATUS_LOADING = 'UPDATE_STATUS_LOADING';
export const UPDATE_PHONE_LOGIN = 'UPDATE_PHONE_LOGIN';
export const UPDATE_ERROR_STATUS_LOGIN = 'UPDATE_ERROR_STATUS_LOGIN';
export const SET_TAB_ACTIVE = 'SET_TAB_ACTIVE';
export const SET_LOCAL_STORAGE_LOGIN = "SET_LOCAL_STORAGE_LOGIN";

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const POST_PROFILE = 'POST_PROFILE';

export const SET_PROVINCES = "SET_PROVINCES";
export const SET_DISTRICTS = "SET_DISTRICTS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_PROVINCE = "UPDATE_PROFILE_PROVINCE";
export const UPDATE_PROFILE_DISTRICT = "UPDATE_PROFILE_DISTRICT";
export const UPDATE_ERROR_STATUS_PROFILE = "UPDATE_ERROR_STATUS_PROFILE";

export const GET_PROVINCES = "GET_PROVINCES";
export const GET_DISTRICTS = "GET_DISTRICTS";